version: "3.9"
services:
  db:
    image: 'postgres:13.3'
    restart: 'always'
    ports:
        - "5432:5432"
    environment: 
        POSTGRES_PASSWORD: example
    volumes: 
        - pgdata:/var/lib/postgresql/data
        - ./initsql/initsql.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  web_app:
    build: .
    restart: always
    ports:
        - 5000:3000
    environment:
        PORT: 3000
        PGHOST: db
        PGDATABASE: postgres
    depends_on:
      db:
        condition: service_healthy
volumes: 
    pgdata:
